DevelopingProgramming/DevelopingComputerProgramming/DoxygenOutput/html/navtree.js File Reference
Functions
function getData (varName)
function stripPath (uri)
function stripPath2 (uri)
function hashValue ()
function hashUrl ()
function pathName ()
function localStorageSupported ()
function storeLink (link)
function deleteLink ()
function cachedLink ()
function getScript (scriptName, func, show)
function createIndent (o, domNode, node, level)
function gotoAnchor (anchor, aname, updateLocation)
function newNode (o, po, text, link, childrenData, lastNode)
function showRoot ()
function expandNode (o, node, imm, showRoot)
function glowEffect (n, duration)
function highlightAnchor ()
function selectAndHighlight (hash, n)
function showNode (o, node, index, hash)
function removeToInsertLater (element)
function getNode (o, po)
function gotoNode (o, subIndex, root, hash, relpath)
function navTo (o, root, hash, relpath)
function showSyncOff (n, relpath)
function showSyncOn (n, relpath)
function toggleSyncButton (relpath)
function initNavTree (toroot, relpath)
Variables
var NAVTREE
var NAVTREEINDEX
var SYNCONMSG = 'click to disable panel synchronisation'
var SYNCOFFMSG = 'click to enable panel synchronisation'
var navTreeSubIndices = new Array()
var animationInProgress = false
Function Documentation
function cachedLink ()
Definition at line 84 of file navtree.js.
References localStorageSupported(), and window.
Referenced by initNavTree(), and navTo().
{
  if (localStorageSupported()) {
    return window.localStorage.getItem('navpath');
  } else {
    return '';
  }
}
function createIndent (o, domNode, node, level)
Definition at line 112 of file navtree.js.
References expandNode().
Referenced by newNode().
{
  var level=-1;
  var n = node;
  while (n.parentNode) { level++; n=n.parentNode; }
  if (node.childrenData) {
    var imgNode = document.createElement("img");
    imgNode.style.paddingLeft=(16*level).toString()+'px';
    imgNode.width = 16;
    imgNode.height = 22;
    imgNode.border = 0;
    node.plus_img = imgNode;
    node.expandToggle = document.createElement("a");
    node.expandToggle.href = "javascript:void(0)";
    node.expandToggle.onclick = function() {
      if (node.expanded) {
        $(node.getChildrenUL()).slideUp("fast");
        node.plus_img.src = node.relpath+"ftv2pnode.png";
        node.expanded = false;
      } else {
        expandNode(o, node, false, false);
      }
    }
    node.expandToggle.appendChild(imgNode);
    domNode.appendChild(node.expandToggle);
    imgNode.src = node.relpath+"ftv2pnode.png";
  } else {
    var span = document.createElement("span");
    span.style.display = 'inline-block';
    span.style.width = 16*(level+1)+'px';
    span.style.height = '22px';
    span.innerHTML = '&#160;';
    domNode.appendChild(span);
  }
}
function deleteLink ()
Definition at line 77 of file navtree.js.
References localStorageSupported(), and window.
Referenced by toggleSyncButton().
{
  if (localStorageSupported()) {
    window.localStorage.setItem('navpath','');
  }
}
function expandNode (o, node, imm, showRoot)
Definition at line 274 of file navtree.js.
References getNode(), getScript(), and showRoot().
Referenced by createIndent(), and showNode().
{
  if (node.childrenData && !node.expanded) {
    if (typeof(node.childrenData)==='string') {
      var varName = node.childrenData;
      getScript(node.relpath+varName,function(){
        node.childrenData = getData(varName);
        expandNode(o, node, imm, showRoot);
      }, showRoot);
    } else {
      if (!node.childrenVisited) {
        getNode(o, node);
      } if (imm || ($.browser.msie && $.browser.version>8)) {
        // somehow slideDown jumps to the start of tree for IE9 :-(
        $(node.getChildrenUL()).show();
      } else {
        $(node.getChildrenUL()).slideDown("fast");
      }
      if (node.isLast) {
        node.plus_img.src = node.relpath+"ftv2mlastnode.png";
      } else {
        node.plus_img.src = node.relpath+"ftv2mnode.png";
      }
      node.expanded = true;
    }
  }
}
function getData (varName)
Definition at line 24 of file navtree.js.
{
  var i = varName.lastIndexOf('/');
  var n = i>=0 ? varName.substring(i+1) : varName;
  return eval(n.replace(/\-/g,'_'));
}
function getNode (o, po)
Definition at line 409 of file navtree.js.
References newNode(), and removeToInsertLater().
Referenced by expandNode(), and showNode().
{
  var insertFunction = removeToInsertLater(po.li);
  po.childrenVisited = true;
  var l = po.childrenData.length-1;
  for (var i in po.childrenData) {
    var nodeData = po.childrenData[i];
    po.children[i] = newNode(o, po, nodeData[0], nodeData[1], nodeData[2],
      i==l);
  }
  insertFunction();
}
function getScript (scriptName, func, show)
Definition at line 93 of file navtree.js.
References showRoot().
Referenced by expandNode(), navTo(), and showNode().
{
  var head = document.getElementsByTagName("head")[0];
  var script = document.createElement('script');
  script.id = scriptName;
  script.type = 'text/javascript';
  script.onload = func;
  script.src = scriptName+'.js';
  if ($.browser.msie && $.browser.version<=8) {
    // script.onload does not work with older versions of IE
    script.onreadystatechange = function() {
      if (script.readyState=='complete' || script.readyState=='loaded') {
        func(); if (show) showRoot();
      }
    }
  }
  head.appendChild(script);
}
function glowEffect (n, duration)
Definition at line 302 of file navtree.js.
Referenced by highlightAnchor(), and navTo().
{
  n.addClass('glow').delay(duration).queue(function(next){
    $(this).removeClass('glow');next();
  });
}
function gotoAnchor (anchor, aname, updateLocation)
Definition at line 150 of file navtree.js.
References animationInProgress, and window.
Referenced by highlightAnchor(), and newNode().
{
  var pos, docContent = $('#doc-content');
  var ancParent = $(anchor.parent());
  if (ancParent.hasClass('memItemLeft') ||
      ancParent.hasClass('fieldname') ||
      ancParent.hasClass('fieldtype') ||
      ancParent.is(':header'))
  {
    pos = ancParent.position().top;
  } else if (anchor.position()) {
    pos = anchor.position().top;
  }
  if (pos) {
    var dist = Math.abs(Math.min(
               pos-docContent.offset().top,
               docContent[0].scrollHeight-
               docContent.height()-docContent.scrollTop()));
    animationInProgress=true;
    docContent.animate({
      scrollTop: pos + docContent.scrollTop() - docContent.offset().top
    },Math.max(50,Math.min(500,dist)),function(){
      if (updateLocation) window.location.href=aname;
      animationInProgress=false;
    });
  }
}
function gotoNode (o, subIndex, root, hash, relpath)
Definition at line 422 of file navtree.js.
References navTo(), NAVTREE, navTreeSubIndices, and showNode().
Referenced by navTo().
{
  var nti = navTreeSubIndices[subIndex][root+hash];
  o.breadcrumbs = $.extend(true, [], nti ? nti : navTreeSubIndices[subIndex][root]);
  if (!o.breadcrumbs && root!=NAVTREE[0][1]) { // fallback: show index
    navTo(o,NAVTREE[0][1],"",relpath);
    $('.item').removeClass('selected');
    $('.item').removeAttr('id');
  }
  if (o.breadcrumbs) {
    o.breadcrumbs.unshift(0); // add 0 for root node
    showNode(o, o.node, 0, hash);
  }
}
function hashUrl ()
Definition at line 49 of file navtree.js.
References hashValue().
Referenced by highlightAnchor(), initNavTree(), and toggleSyncButton().
{
  return '#'+hashValue();
}
function hashValue ()
Definition at line 44 of file navtree.js.
Referenced by hashUrl(), highlightAnchor(), and initNavTree().
{
  return $(location).attr('hash').substring(1).replace(/[^\w\-]/g,'');
}
function highlightAnchor ()
Definition at line 309 of file navtree.js.
References glowEffect(), gotoAnchor(), hashUrl(), and hashValue().
Referenced by selectAndHighlight().
{
  var aname = hashUrl();
  var anchor = $(aname);
  if (anchor.parent().attr('class')=='memItemLeft'){
    var rows = $('.memberdecls tr[class$="'+hashValue()+'"]');
    glowEffect(rows.children(),300); // member without details
  } else if (anchor.parent().attr('class')=='fieldname'){
    glowEffect(anchor.parent().parent(),1000); // enum value
  } else if (anchor.parent().attr('class')=='fieldtype'){
    glowEffect(anchor.parent().parent(),1000); // struct field
  } else if (anchor.parent().is(":header")) {
    glowEffect(anchor.parent(),1000); // section header
  } else {
    glowEffect(anchor.next(),1000); // normal member
  }
  gotoAnchor(anchor,aname,false);
}
function initNavTree (toroot, relpath)
Definition at line 491 of file navtree.js.
References a, animationInProgress, cachedLink(), hashUrl(), hashValue(), localStorageSupported(), navTo(), NAVTREE, pathName(), showRoot(), showSyncOff(), showSyncOn(), stripPath(), stripPath2(), toggleSyncButton(), and window.
{
  var o = new Object();
  o.toroot = toroot;
  o.node = new Object();
  o.node.li = document.getElementById("nav-tree-contents");
  o.node.childrenData = NAVTREE;
  o.node.children = new Array();
  o.node.childrenUL = document.createElement("ul");
  o.node.getChildrenUL = function() { return o.node.childrenUL; };
  o.node.li.appendChild(o.node.childrenUL);
  o.node.depth = 0;
  o.node.relpath = relpath;
  o.node.expanded = false;
  o.node.isLast = true;
  o.node.plus_img = document.createElement("img");
  o.node.plus_img.src = relpath+"ftv2pnode.png";
  o.node.plus_img.width = 16;
  o.node.plus_img.height = 22;
  if (localStorageSupported()) {
    var navSync = $('#nav-sync');
    if (cachedLink()) {
      showSyncOff(navSync,relpath);
      navSync.removeClass('sync');
    } else {
      showSyncOn(navSync,relpath);
    }
    navSync.click(function(){ toggleSyncButton(relpath); });
  }
  $(window).load(function(){
    navTo(o,toroot,hashUrl(),relpath);
    showRoot();
  });
  $(window).bind('hashchange', function(){
     if (window.location.hash && window.location.hash.length>1){
       var a;
       if ($(location).attr('hash')){
         var clslink=stripPath(pathName())+':'+hashValue();
         a=$('.item a[class$="'+clslink.replace(/</g,'\\3c ')+'"]');
       }
       if (a==null || !$(a).parent().parent().hasClass('selected')){
         $('.item').removeClass('selected');
         $('.item').removeAttr('id');
       }
       var link=stripPath2(pathName());
       navTo(o,link,hashUrl(),relpath);
     } else if (!animationInProgress) {
       $('#doc-content').scrollTop(0);
       $('.item').removeClass('selected');
       $('.item').removeAttr('id');
       navTo(o,toroot,hashUrl(),relpath);
     }
  })
}
function localStorageSupported ()
Definition at line 59 of file navtree.js.
References window.
Referenced by cachedLink(), deleteLink(), initNavTree(), and storeLink().
{
  try {
    return 'localStorage' in window && window['localStorage'] !== null &&
      window.localStorage.getItem;
  }
  catch(e) {
    return false;
  }
}
function navTo (o, root, hash, relpath)
Definition at line 437 of file navtree.js.
References cachedLink(), getScript(), glowEffect(), gotoNode(), NAVTREE, NAVTREEINDEX, and navTreeSubIndices.
Referenced by gotoNode(), and initNavTree().
{
  var link = cachedLink();
  if (link) {
    var parts = link.split('#');
    root = parts[0];
    if (parts.length>1) hash = '#'+parts[1].replace(/[^\w\-]/g,'');
    else hash='';
  }
  if (hash.match(/^#l\d+$/)) {
    var anchor=$('a[name='+hash.substring(1)+']');
    glowEffect(anchor.parent(),1000); // line number
    hash=''; // strip line number anchors
  }
  var url=root+hash;
  var i=-1;
  while (NAVTREEINDEX[i+1]<=url) i++;
  if (i==-1) { i=0; root=NAVTREE[0][1]; } // fallback: show index
  if (navTreeSubIndices[i]) {
    gotoNode(o,i,root,hash,relpath)
  } else {
    getScript(relpath+'navtreeindex'+i,function(){
      navTreeSubIndices[i] = eval('NAVTREEINDEX'+i);
      if (navTreeSubIndices[i]) {
        gotoNode(o,i,root,hash,relpath);
      }
    },true);
  }
}
function newNode (o, po, text, link, childrenData, lastNode)
Definition at line 178 of file navtree.js.
References a, createIndent(), gotoAnchor(), pathName(), storeLink(), and stripPath().
Referenced by getNode().
{
  var node = new Object();
  node.children = Array();
  node.childrenData = childrenData;
  node.depth = po.depth + 1;
  node.relpath = po.relpath;
  node.isLast = lastNode;
  node.li = document.createElement("li");
  po.getChildrenUL().appendChild(node.li);
  node.parentNode = po;
  node.itemDiv = document.createElement("div");
  node.itemDiv.className = "item";
  node.labelSpan = document.createElement("span");
  node.labelSpan.className = "label";
  createIndent(o,node.itemDiv,node,0);
  node.itemDiv.appendChild(node.labelSpan);
  node.li.appendChild(node.itemDiv);
  var a = document.createElement("a");
  node.labelSpan.appendChild(a);
  node.label = document.createTextNode(text);
  node.expanded = false;
  a.appendChild(node.label);
  if (link) {
    var url;
    if (link.substring(0,1)=='^') {
      url = link.substring(1);
      link = url;
    } else {
      url = node.relpath+link;
    }
    a.className = stripPath(link.replace('#',':'));
    if (link.indexOf('#')!=-1) {
      var aname = '#'+link.split('#')[1];
      var srcPage = stripPath(pathName());
      var targetPage = stripPath(link.split('#')[0]);
      a.href = srcPage!=targetPage ? url : "javascript:void(0)";
      a.onclick = function(){
        storeLink(link);
        if (!$(a).parent().parent().hasClass('selected'))
        {
          $('.item').removeClass('selected');
          $('.item').removeAttr('id');
          $(a).parent().parent().addClass('selected');
          $(a).parent().parent().attr('id','selected');
        }
        var anchor = $(aname);
        gotoAnchor(anchor,aname,true);
      };
    } else {
      a.href = url;
      a.onclick = function() { storeLink(link); }
    }
  } else {
    if (childrenData != null)
    {
      a.className = "nolink";
      a.href = "javascript:void(0)";
      a.onclick = node.expandToggle.onclick;
    }
  }
  node.childrenUL = null;
  node.getChildrenUL = function() {
    if (!node.childrenUL) {
      node.childrenUL = document.createElement("ul");
      node.childrenUL.className = "children_ul";
      node.childrenUL.style.display = "none";
      node.li.appendChild(node.childrenUL);
    }
    return node.childrenUL;
  };
  return node;
}
function pathName ()
Definition at line 54 of file navtree.js.
Referenced by initNavTree(), newNode(), selectAndHighlight(), and toggleSyncButton().
{
  return $(location).attr('pathname').replace(/[^-A-Za-z0-9+&@#/%?=~_|!:,.;\(\)]/g, '');
}
function removeToInsertLater (element)
Definition at line 396 of file navtree.js.
Referenced by getNode().
                                      {
  var parentNode = element.parentNode;
  var nextSibling = element.nextSibling;
  parentNode.removeChild(element);
  return function() {
    if (nextSibling) {
      parentNode.insertBefore(element, nextSibling);
    } else {
      parentNode.appendChild(element);
    }
  };
}
function selectAndHighlight (hash, n)
Definition at line 328 of file navtree.js.
References a, css, highlightAnchor(), pathName(), showRoot(), and stripPath().
Referenced by showNode().
{
  var a;
  if (hash) {
    var link=stripPath(pathName())+':'+hash.substring(1);
    a=$('.item a[class$="'+link+'"]');
  }
  if (a && a.length) {
    a.parent().parent().addClass('selected');
    a.parent().parent().attr('id','selected');
    highlightAnchor();
  } else if (n) {
    $(n.itemDiv).addClass('selected');
    $(n.itemDiv).attr('id','selected');
  }
  if ($('#nav-tree-contents .item:first').hasClass('selected')) {
    $('#nav-sync').css('top','30px');
  } else {
    $('#nav-sync').css('top','5px');
  }
  showRoot();
}
function showNode (o, node, index, hash)
Definition at line 351 of file navtree.js.
References css, expandNode(), getNode(), getScript(), selectAndHighlight(), and stripPath().
Referenced by gotoNode().
{
  if (node && node.childrenData) {
    if (typeof(node.childrenData)==='string') {
      var varName = node.childrenData;
      getScript(node.relpath+varName,function(){
        node.childrenData = getData(varName);
        showNode(o,node,index,hash);
      },true);
    } else {
      if (!node.childrenVisited) {
        getNode(o, node);
      }
      $(node.getChildrenUL()).css({'display':'block'});
      if (node.isLast) {
        node.plus_img.src = node.relpath+"ftv2mlastnode.png";
      } else {
        node.plus_img.src = node.relpath+"ftv2mnode.png";
      }
      node.expanded = true;
      var n = node.children[o.breadcrumbs[index]];
      if (index+1<o.breadcrumbs.length) {
        showNode(o,n,index+1,hash);
      } else {
        if (typeof(n.childrenData)==='string') {
          var varName = n.childrenData;
          getScript(n.relpath+varName,function(){
            n.childrenData = getData(varName);
            node.expanded=false;
            showNode(o,node,index,hash); // retry with child node expanded
          },true);
        } else {
          var rootBase = stripPath(o.toroot.replace(/\..+$/, ''));
          if (rootBase=="index" || rootBase=="pages" || rootBase=="search") {
            expandNode(o, n, true, true);
          }
          selectAndHighlight(hash,n);
        }
      }
    }
  } else {
    selectAndHighlight(hash);
  }
}
function showRoot ()
Definition at line 259 of file navtree.js.
References navtree, and window.
Referenced by expandNode(), getScript(), initNavTree(), and selectAndHighlight().
{
  var headerHeight = $("#top").height();
  var footerHeight = $("#nav-path").height();
  var windowHeight = $(window).height() - headerHeight - footerHeight;
  (function (){ // retry until we can scroll to the selected item
    try {
      var navtree=$('#nav-tree');
      navtree.scrollTo('#selected',0,{offset:-windowHeight/2});
    } catch (err) {
      setTimeout(arguments.callee, 0);
    }
  })();
}
function showSyncOff (n, relpath)
Definition at line 467 of file navtree.js.
References SYNCOFFMSG.
Referenced by initNavTree(), and toggleSyncButton().
{
    n.html('<img src="'+relpath+'sync_off.png" title="'+SYNCOFFMSG+'"/>');
}
function showSyncOn (n, relpath)
Definition at line 472 of file navtree.js.
References SYNCONMSG.
Referenced by initNavTree(), and toggleSyncButton().
{
    n.html('<img src="'+relpath+'sync_on.png" title="'+SYNCONMSG+'"/>');
}
function storeLink (link)
Definition at line 70 of file navtree.js.
References localStorageSupported(), and window.
Referenced by newNode(), and toggleSyncButton().
{
  if (!$("#nav-sync").hasClass('sync') && localStorageSupported()) {
      window.localStorage.setItem('navpath',link);
  }
}
function stripPath (uri)
Definition at line 31 of file navtree.js.
Referenced by initNavTree(), newNode(), selectAndHighlight(), and showNode().
{
  return uri.substring(uri.lastIndexOf('/')+1);
}
function stripPath2 (uri)
Definition at line 36 of file navtree.js.
Referenced by initNavTree(), and toggleSyncButton().
{
  var i = uri.lastIndexOf('/');
  var s = uri.substring(i+1);
  var m = uri.substring(0,i+1).match(/\/d\w\/d\w\w\/$/);
  return m ? uri.substring(i-6) : s;
}
function toggleSyncButton (relpath)
Definition at line 477 of file navtree.js.
References deleteLink(), hashUrl(), pathName(), showSyncOff(), showSyncOn(), storeLink(), and stripPath2().
Referenced by initNavTree().
{
  var navSync = $('#nav-sync');
  if (navSync.hasClass('sync')) {
    navSync.removeClass('sync');
    showSyncOff(navSync,relpath);
    storeLink(stripPath2(pathName())+hashUrl());
  } else {
    navSync.addClass('sync');
    showSyncOn(navSync,relpath);
    deleteLink();
  }
}
Variable Documentation
var animationInProgress = false
Definition at line 148 of file navtree.js.
Referenced by gotoAnchor(), and initNavTree().
var NAVTREE
Initial value:
=
[
  [ "Calculator", "index.html", [
    [ "Developing-Computer-Programming-Program-Elements-Structure", "
      md___users_nishantjain__desktop__developing_computer_programming__r_e_a_d_m_e.html", null ],
    [ "Files", null, [
      [ "File List", "files.html", "files" ],
      [ "Globals", "globals.html", [
        [ "All", "globals.html", null ],
        [ "Functions", "globals_func.html", null ]
      ] ]
    ] ]
  ] ]
]
Definition at line 1 of file navtree.js.
Referenced by gotoNode(), initNavTree(), and navTo().
var NAVTREEINDEX
Initial value:
=
[
"_expression_calc_8c.html"
]
Definition at line 15 of file navtree.js.
Referenced by navTo().
var navTreeSubIndices = new Array()
Definition at line 22 of file navtree.js.
Referenced by gotoNode(), and navTo().
var SYNCOFFMSG = 'click to enable panel synchronisation'
Definition at line 21 of file navtree.js.
Referenced by showSyncOff().
var SYNCONMSG = 'click to disable panel synchronisation'
Definition at line 20 of file navtree.js.
Referenced by showSyncOn().