DevelopingProgramming/DevelopingComputerProgramming/DoxygenOutput/html/resize.js File Reference
Functions
function readCookie (cookie)
function writeCookie (cookie, val, expiration)
function resizeWidth ()
function restoreWidth (navWidth)
function resizeHeight ()
function initResizable ()
Variables
var cookie_namespace = 'doxygen'
var sidenav
var navtree
var content
var header
Function Documentation
function initResizable ()
Definition at line 62 of file resize.js.
References content, css, header, navtree, readCookie(), resizeHeight(), resizeWidth(), restoreWidth(), sidenav, and window.
{
  header = $("#top");
  sidenav = $("#side-nav");
  content = $("#doc-content");
  navtree = $("#nav-tree");
  footer = $("#nav-path");
  $(".side-nav-resizable").resizable({resize: function(e, ui) { resizeWidth(); } });
  $(window).resize(function() { resizeHeight(); });
  var width = readCookie('width');
  if (width) { restoreWidth(width); } else { resizeWidth(); }
  resizeHeight();
  var url = location.href;
  var i=url.indexOf("#");
  if (i>=0) window.location.hash=url.substr(i);
  var _preventDefault = function(evt) { evt.preventDefault(); };
  $("#splitbar").bind("dragstart", _preventDefault).bind("selectstart", _preventDefault);
  $(document).bind('touchmove',function(e){
    var device = navigator.userAgent.toLowerCase();
    var ios = device.match(/(iphone|ipod|ipad)/);
    if (ios) {
      try {
        var target = e.target;
        while (target) {
          if ($(target).css('-webkit-overflow-scrolling')=='touch') return;
          target = target.parentNode;
        }
        e.preventDefault();
      } catch(err) {
        e.preventDefault();
      }
    }
  });
}
function readCookie (cookie)
Definition at line 4 of file resize.js.
References cookie_namespace.
Referenced by initResizable().
{
  var myCookie = cookie_namespace+"_"+cookie+"=";
  if (document.cookie)
  {
    var index = document.cookie.indexOf(myCookie);
    if (index != -1)
    {
      var valStart = index + myCookie.length;
      var valEnd = document.cookie.indexOf(";", valStart);
      if (valEnd == -1)
      {
        valEnd = document.cookie.length;
      }
      var val = document.cookie.substring(valStart, valEnd);
      return val;
    }
  }
  return 0;
}
function resizeHeight ()
Definition at line 52 of file resize.js.
References content, header, navtree, sidenav, and window.
Referenced by initResizable().
{
  var headerHeight = header.outerHeight();
  var footerHeight = footer.outerHeight();
  var windowHeight = $(window).height() - headerHeight - footerHeight;
  content.css({height:windowHeight + "px"});
  navtree.css({height:windowHeight + "px"});
  sidenav.css({height:windowHeight + "px",top: headerHeight+"px"});
}
function resizeWidth ()
Definition at line 37 of file resize.js.
References content, sidenav, window, and writeCookie().
Referenced by initResizable().
{
  var windowWidth = $(window).width() + "px";
  var sidenavWidth = $(sidenav).outerWidth();
  content.css({marginLeft:parseInt(sidenavWidth)+"px"});
  writeCookie('width',sidenavWidth, null);
}
function restoreWidth (navWidth)
Definition at line 45 of file resize.js.
References content, sidenav, and window.
Referenced by initResizable().
{
  var windowWidth = $(window).width() + "px";
  content.css({marginLeft:parseInt(navWidth)+6+"px"});
  sidenav.css({width:navWidth + "px"});
}
function writeCookie (cookie, val, expiration)
Definition at line 25 of file resize.js.
References cookie_namespace.
Referenced by resizeWidth().
{
  if (val==undefined) return;
  if (expiration == null)
  {
    var date = new Date();
    date.setTime(date.getTime()+(10*365*24*60*60*1000)); // default expiration is one week
    expiration = date.toGMTString();
  }
  document.cookie = cookie_namespace + "_" + cookie + "=" + val + "; expires=" + expiration
      +"; path=/";
}
Variable Documentation
var content
Definition at line 2 of file resize.js.
Referenced by initResizable(), resizeHeight(), resizeWidth(), restoreWidth(), and toggleVisibility().
var cookie_namespace = 'doxygen'
Definition at line 1 of file resize.js.
Referenced by readCookie(), and writeCookie().
var header
Definition at line 2 of file resize.js.
Referenced by initResizable(), and resizeHeight().
var navtree
Definition at line 2 of file resize.js.
Referenced by initResizable(), resizeHeight(), and showRoot().
var sidenav
Definition at line 2 of file resize.js.
Referenced by initResizable(), resizeHeight(), resizeWidth(), and restoreWidth().